language: node_js
node_js: 6.10.3
hexo: 3.3.6

# S: Build Lifecycle
install:
  - npm install

#before_script:
 # - npm install -g gulp

script:
- hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "hysg"
  - git config user.email "ldr95324@126.com"
  - git add .
  - git commit -m "update post"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - source
env:
 global:
   - GH_REF: github.com/hysg/hysg.github.io.git
